apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: acs-image-scan-
  namespace: acs-pipeline
spec:
  pipelineRef:
    name: acs-image-scan
  params:
    - name: image
      value: "registry.redhat.io/ubi9/ubi-minimal:latest"
